import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const EN_MANIFEST_PATH = 'data/en-manifest.json';
const TRANSLATE_ENDPOINT =
  'https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=te&dt=t&q=';

const independentVowels = {
  अ: 'అ',
  आ: 'ఆ',
  इ: 'ఇ',
  ई: 'ఈ',
  उ: 'ఉ',
  ऊ: 'ఊ',
  ऋ: 'ఋ',
  ॠ: 'ౠ',
  ऌ: 'ఌ',
  ए: 'ఏ',
  ऐ: 'ఐ',
  ओ: 'ఓ',
  औ: 'ఔ',
};

const vowelSigns = {
  'ा': 'ా',
  'ि': 'ి',
  'ी': 'ీ',
  'ु': 'ు',
  'ू': 'ూ',
  'ृ': 'ృ',
  'ॄ': 'ౄ',
  'ॢ': 'ౢ',
  'े': 'ే',
  'ै': 'ై',
  'ो': 'ో',
  'ौ': 'ౌ',
};

const consonants = {
  क: 'క',
  ख: 'ఖ',
  ग: 'గ',
  घ: 'ఘ',
  ङ: 'ఙ',
  च: 'చ',
  छ: 'ఛ',
  ज: 'జ',
  झ: 'ఝ',
  ञ: 'ఞ',
  ट: 'ట',
  ठ: 'ఠ',
  ड: 'డ',
  ढ: 'ఢ',
  ण: 'ణ',
  त: 'త',
  थ: 'థ',
  द: 'ద',
  ध: 'ధ',
  न: 'న',
  प: 'ప',
  फ: 'ఫ',
  ब: 'బ',
  भ: 'భ',
  म: 'మ',
  य: 'య',
  र: 'ర',
  ल: 'ల',
  व: 'వ',
  श: 'శ',
  ष: 'ష',
  स: 'స',
  ह: 'హ',
  ळ: 'ళ',
  क्ष: 'క్ష',
  ज्ञ: 'జ్ఞ',
};

const misc = {
  'ं': 'ం',
  'ः': 'ః',
  'ँ': 'ఁ',
  'ॐ': 'ఓం',
  '।': '।',
  '॥': '॥',
  '0': '0',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
};

function cleanText(value) {
  return String(value || '')
    .replace(/\r/g, '')
    .replace(/\u00a0/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function transliterateToTelugu(text) {
  let output = '';

  for (let index = 0; index < text.length; index += 1) {
    const pair = text.slice(index, index + 2);
    if (pair === 'क्ष' || pair === 'ज्ञ') {
      output += consonants[pair];
      index += 1;
      continue;
    }

    const char = text[index];
    const next = text[index + 1];

    if (independentVowels[char]) {
      output += independentVowels[char];
      continue;
    }

    if (consonants[char]) {
      output += consonants[char];
      if (next === '्') {
        output += '్';
        index += 1;
        continue;
      }
      if (vowelSigns[next]) {
        output += vowelSigns[next];
        index += 1;
        continue;
      }
      continue;
    }

    if (vowelSigns[char]) {
      output += vowelSigns[char];
      continue;
    }

    if (misc[char]) {
      output += misc[char];
      continue;
    }

    output += char;
  }

  return output;
}

async function translateBatch(lines) {
  const joined = lines.join('\n[[BH_SPLIT]]\n');
  const response = await fetch(`${TRANSLATE_ENDPOINT}${encodeURIComponent(joined)}`);
  if (!response.ok) {
    throw new Error(`Translation request failed with ${response.status}`);
  }

  const payload = await response.json();
  const translated = payload[0].map((part) => part[0]).join('');
  return translated.split('\n[[BH_SPLIT]]\n');
}

async function translateAll(items, label) {
  const sanitized = items.map((item) => cleanText(item));
  const results = [];
  const chunkSize = 20;

  for (let index = 0; index < sanitized.length; index += chunkSize) {
    const chunk = sanitized.slice(index, index + chunkSize);
    const translated = await translateBatch(chunk);
    results.push(...translated);
    process.stdout.write(
      `Translated ${label} ${Math.min(index + chunk.length, sanitized.length)}/${sanitized.length}\r`
    );
  }

  process.stdout.write('\n');
  return results.map(cleanText);
}

function toTeluguPath(englishPath) {
  return englishPath.replace(/^data\/en-/, 'data/te-');
}

function teluguTitle(cantoNumber, chapterNumber) {
  return `స్కంధము ${cantoNumber} అధ్యాయం ${chapterNumber}`;
}

async function main() {
  mkdirSync('data', { recursive: true });

  const englishManifest = JSON.parse(readFileSync(EN_MANIFEST_PATH, 'utf8'));
  const teluguManifest = {
    generatedAt: new Date().toISOString(),
    source: englishManifest.source,
    status: 'machine-translated',
    note: 'Telugu reader generated by transliterating Sanskrit text into Telugu script and translating English meanings/notes into Telugu.',
    cantos: englishManifest.cantos.map((canto) => ({
      cantoNumber: canto.cantoNumber,
      title: `స్కంధము ${canto.cantoNumber}`,
      chapters: canto.chapters.map((chapter) => ({
        chapterNumber: chapter.chapterNumber,
        title: teluguTitle(canto.cantoNumber, chapter.chapterNumber),
        verseCount: chapter.verseCount,
        path: toTeluguPath(chapter.path),
      })),
    })),
  };

  for (const canto of englishManifest.cantos) {
    for (const chapter of canto.chapters) {
      const englishChapter = JSON.parse(readFileSync(chapter.path, 'utf8'));
      const meaningSource = englishChapter.verses.map((verse) => verse.meaning || '');
      const notesSource = englishChapter.verses.map(
        (verse) => verse.wordMeanings || verse.purport || englishChapter.sourceNote || ''
      );
      const teluguMeanings = await translateAll(
        meaningSource,
        `meanings C${canto.cantoNumber} Ch${chapter.chapterNumber}`
      );
      const teluguNotes = await translateAll(
        notesSource,
        `notes C${canto.cantoNumber} Ch${chapter.chapterNumber}`
      );

      const teluguChapter = {
        cantoNumber: englishChapter.cantoNumber,
        chapterNumber: englishChapter.chapterNumber,
        title: teluguTitle(englishChapter.cantoNumber, englishChapter.chapterNumber),
        summary: `స్కంధము ${englishChapter.cantoNumber} లోని అధ్యాయం ${englishChapter.chapterNumber} కోసం తెలుగు పఠన నిర్మాణం.`,
        sourceNote:
          'ఈ అధ్యాయం యాంత్రిక అనువాదంతో రూపొందించబడింది. భావం సహాయార్థం, మూల పాఠ్య నిర్ధారణకు ఇంగ్లీషు ఆధారాన్ని కూడా పరిశీలించాలి.',
        verses: englishChapter.verses.map((verse, index) => ({
          verseNumber: verse.verseNumber,
          text: transliterateToTelugu(verse.text),
          transliteration: verse.transliteration,
          meaning: teluguMeanings[index],
          wordMeanings: teluguNotes[index],
        })),
      };

      writeFileSync(toTeluguPath(chapter.path), JSON.stringify(teluguChapter, null, 2));
      console.log(`Built Telugu ${toTeluguPath(chapter.path)}`);
    }
  }

  writeFileSync('data/te-manifest.json', JSON.stringify(teluguManifest, null, 2));
  console.log('Built Telugu manifest.');
}

await main();
